# Generated by Django 2.1.5 on 2019-01-13 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pontoturistico_cometario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='cometario',
            new_name='comentario',
        ),
    ]
