# Generated by Django 2.1.5 on 2019-01-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0005_auto_20190112_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='comentario',
            new_name='comentarios',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.Avaliacao'),
        ),
    ]
